<a href="https://colab.research.google.com/github/tugcegurbuz/DeepLearning_TF/blob/master/DL_TF_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Description:** In this lab we will deal with basic, silly TensorFlow. 

*Learning Objectives:  building a graph, defining constants and variables, defining operation and place holders* 

Reference: https://labs.cognitiveclass.ai/tools/jupyterlab/lab/tree/labs/ML0120EN/ML0120EN-1.1-Review-TensorFlow-Hello-World.ipynb

Prepared by Tugce Gurbuz

In [0]:
import tensorflow as tf

**1)  0 Dimensional Arrays**

Graph1 will show how to define a 0 dimensional array

In [0]:
#TensorFlow works as a graph computational model. Let's create our first graph which we named as graph1
graph1 = tf.Graph()

In [0]:
#Define 0 dimensional (scalar value) 2 constants: a and b.
with graph1.as_default():
    a = tf.constant([2], name = 'constant_a')
    b = tf.constant([3], name = 'constant_b')

For example, calling tf.constant([2], name = 'constant_a') adds a single tf.Operation to the default graph. This operation produces the value 2, and returns a tf.Tensor that represents the value of the constant.

In [66]:
#Let's see constant a and b
a, b

(<tf.Tensor 'constant_a_1:0' shape=(1,) dtype=int32>,
 <tf.Tensor 'constant_b_1:0' shape=(1,) dtype=int32>)

As you see, it prints just name, shape and type of the tensor. Now we will print the value of the constant when we run them in tensorflow **session**.

Steps: Open session --> Run the session --> Close the session

In [6]:
# Printing the value of a and b
sess = tf.Session(graph = graph1)
result_a = sess.run(a)
result_b = sess.run(b)

print('Result of a %d and result of b %d' %(result_a, result_b))
sess.close()  

Result of a 2 and result of b 3


In [0]:
#Let's make operation with the constants!
#Let's add constant a and b with tf.add(). c = a + b

with graph1.as_default():
  c = tf.add(a, b)


In [65]:
#Let's see c
c

<tf.Tensor 'Add_1:0' shape=(1,) dtype=int32>

Again, to see the result of the c, we need to run a **session**. In this sense, sessions are defined as the context in which we form the data flow graphs.

In [23]:
sess = tf.Session(graph = graph1)
result_c = sess.run(c)
print('Result of c is %d' %result_c)
sess.close()

Result of c is 5


If you don't want to close every time you run a session, you can run it inside a with-block. So, it will close it automatically!

In [0]:
#Running sessions inside of a with block

with tf.Session(graph = graph1) as sess:
  result_a = sess.run(a)
  result_b = sess.run(b)
  result_c = sess.run(c)

In [25]:
#Let's see results
print('Result of a is %d; result of b is %d; result of c is %d' %(result_a, result_b, result_c))

Result of a is 2; result of b is 3; result of c is 5


**2) Multidimensional Arrays**

Graph2 will show how to define arrays with different dimensions.

Graph3 will show how to define operations with multiple dimensions

In [0]:
#Define Graph2
graph2 = tf.Graph()

In [0]:
#Add constants
with graph2.as_default():
    Scalar = tf.constant(2) #0 dimensional
    Vector = tf.constant([5,6,2]) #1 dimensional
    Matrix = tf.constant([
                          [1,2,3],
                          [2,3,4],
                          [3,4,5]
                          ]) #2 dimensional
    Tensor = tf.constant([
                          [[1,2,3],[2,3,4],[3,4,5]],
                          [[4,5,6],[5,6,7],[6,7,8]],
                          [[7,8,9],[8,9,10],[9,10,11]]
                          ]) #3 dimensional

In [35]:
#Let's see our arrays of different dimensions
Scalar, Vector, Matrix, Tensor

(<tf.Tensor 'Const_12:0' shape=() dtype=int32>,
 <tf.Tensor 'Const_13:0' shape=(3,) dtype=int32>,
 <tf.Tensor 'Const_14:0' shape=(3, 3) dtype=int32>,
 <tf.Tensor 'Const_15:0' shape=(3, 3, 3) dtype=int32>)

In [39]:
#tf.shape gives the shape of the values:
Scalar.shape, Vector.shape, Matrix.shape, Tensor.shape

(TensorShape([]),
 TensorShape([Dimension(3)]),
 TensorShape([Dimension(3), Dimension(3)]),
 TensorShape([Dimension(3), Dimension(3), Dimension(3)]))

In [31]:
#Run sessions
with tf.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = sess.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = sess.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = sess.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 2 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [59]:
#Let's define a operation for 3 matrices with graph3:
#First we will add 3 matrices, then we will do matrix multiplication

#Define graph3
graph3 = tf.Graph()

#Define matrices
with graph3.as_default():
  matrix1 = tf.constant([
                         [1, 0, 0],
                         [0, 1, 0],
                         [0, 0, 1]
                        ])
  
  matrix2 = tf.constant([
                       [2, 6, 0],
                       [-3, 3, 9],
                       [2, 4, 11]
                      ])
  matrix3 = tf.constant([
                       [11, -4, 5],
                       [1, -34, 26],
                       [2, 9, -3]
                      ])
  
  #add them
  matrix4 = matrix1 + matrix2 + matrix3
  
  #matrix multiplication
  mul_operation = tf.matmul(tf.matmul(matrix1, matrix2), matrix3)
  
#Define session
with tf.Session(graph = graph3) as sess:
  result = sess.run(matrix4)
  print('Addition of matrices is equal to \n %s' %result)
  result = sess.run(mul_operation)
  print('Matrix multiplication of matrices is equal to \n %s' %result)
  
  ##Note: * symbol does element wise multiplication known as Hadamard 
  ##multiplication

Addition of matrices is equal to 
 [[ 14   2   5]
 [ -2 -30  35]
 [  4  13   9]]
Matrix multiplication of matrices is equal to 
 [[  28 -212  166]
 [ -12   -9   36]
 [  48  -45   81]]


**3) Variables **

You cannot update constants, but you can update variables through each session.

In [0]:
#define variable
x = tf.Variable(0)

In [70]:
#Let's see our variable
x

<tf.Variable 'Variable_2:0' shape=() dtype=int32_ref>

In [0]:
#Let's update our variable
#Assign function simply takes reference value and updated value

update = tf.assign(x, x+1)

In [0]:
#To be able to use variables in a computation graph it is necessary to 
#initialize them before running the graph in a session. 
#This is done by running tf.global_variables_initializer().

init_op = tf.global_variables_initializer()

In [80]:
#Let's run a session and update our variable during the session
with tf.Session() as sess:
    sess.run(init_op)
    print('Reference value is %s\n' %sess.run(x))
    
    for i in range(3):
        sess.run(update)
        print('Updated value is %s\n' %sess.run(x))

Reference value is 0

Updated value is 1

Updated value is 2

Updated value is 3



**4) Placeholders**

What abou feeding data outside of the TensorFlow graph? **Placeholders** are kind of holes in your graph that you can pass data.

In [0]:
#Define a placeholder
#It takes datatype as an input
h = tf.placeholder(tf.float32)

In [82]:
#Let's see our place holder
h

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>

In [84]:
#Let's define a simple adding operation
ho = h * 2
ho

<tf.Tensor 'mul_1:0' shape=<unknown> dtype=float32>

In [86]:
#To pass the data into the model we call the session with an extra argument 
#"feed_dict" in which we should pass a dictionary with each placeholder name 
#followed by its respective data, just like this:

with tf.Session() as sess:
    result = sess.run(ho,feed_dict={h:3.5})
    print ('Passed data resulted %s\n' %result)

Passed data resulted 7.0



In [90]:
#We can also pass more dimensional data from the operation
dictionary={h: [ 
                 [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ], 
                 [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] 
                 ] 
           }

with tf.Session() as sess:
    result = sess.run(ho,feed_dict=dictionary)
    print ('Passed data resulted \n%s\n' %result)

Passed data resulted 
[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]



**5) Operations**

More operations can be found from: https://www.tensorflow.org/api_docs/python